import numpy as np

from core import navigationEquations, kinematicEquations, translationalEquations, rotationalEquations
from core import rk4
from aerodynamics import aerodynamicForceWind, aerodynamicForceBody
from utilities import atmosphereGravityModel

atmosphereGravityModel.initialize()

cos = np.cos
sin = np.sin
tan = np.tan

def makeStateEq(model, control_input):
	def f(state_variables, t):
		''' Returns the RHS of the state equation (dx/dt = f(x,t)) using the 
			equations of motion of a 6 DOF aircraft.

			Assumptions: Flat earth, symetric airplane (Ixy = Iyz = 0), 
			
		:param x: State variables values
		:param t: Time instant (not used)
		'''

		# ATRIBUTING NAMES TO STATE VARIABLES

		# CG POSITION (NED)
		xE, yE, zE = state_variables.positions  # alias
		yE = x[1]
		zE = x[2]

		# ATTITUDE
		phi = x[3]
		tet = x[4]
		psi = x[5]

		# VELOCITY (BODY AXIS)
		u = x[6]
		v = x[7]
		w = x[8]

		# ANGULAR VELOCITY
		p = x[9]
		q = x[10]
		r = x[11]

		# INTERPOLATE VALUES OF AIR DENSITY AND GRAVITY FOR VALIDATION
		altitude = -zE # (Z IS POINTED DOWNWARDS)
		
		rho = atmosphereGravityModel.getDensity(altitude)
		g   = atmosphereGravityModel.getGravity(altitude)

		#rho = 1.225
		#g = 9.81

		# AIRSPEED AND DYNAMIC PRESSURE
		V = np.sqrt(u*u + v*v + w*w)
		dynPres = 0.5*rho*V**2
		
		# AERODYNAMIC ANGLES (ALFA, BETA)
		eps = 1e-8
		if V < eps:
			V = eps
			alfa = 0.0
			beta = 0.0
		else:
			alfa = np.arctan2(w, u)
			beta = np.arcsin(v/V)

		# PRE CALCULATE TRIGONOMETRIC FUNCTIONS
		sphi = sin(phi)
		cphi = cos(phi)
		stet = sin(tet)
		ctet = cos(tet)
		ttet = tan(tet)
		spsi = sin(psi)
		cpsi = cos(psi)
		salfa = sin(alfa)
		calfa = cos(alfa)
		sbeta = sin(beta)
		cbeta =	cos(beta)


		ele_cmd, ail_cmd, rud_cmd, throttle_cmd, brake_cmd = control_input()

		el  = 10 * ele_cmd
		ail = 30 * ail_cmd
		rud = 10 * rud_cmd
		throttle = throttle_cmd
		brake = brake_cmd* 200

		def THRUST(throttle, V, rho):
			
			return throttle*((-0.0005*V**3 - 0.0053*V**2 - 0.928*V + 38.37)*rho/1.225) #MODEL BASED ON EXPERIMENTS
		
		def BRAKE(brake):
			bm = 100/(200**2)
			return bm * brake**2
		
		arm_z_engine = -0.05 # (distance from CG to engine thrust line, positive downwards)

		D, L, C, l, m, n = aerodynamicForceWind(model, alfa, beta, p, q, r, el, ail, rud, V, dynPres)

		X, Y, Z = aerodynamicForceBody(D, L, C, salfa, calfa, sbeta, cbeta)
		m = m + arm_z_engine * THRUST(throttle, V, rho) # (considering the moment generated by the thrust if it is not applied in line with the CG)
		X = X + THRUST(throttle, V, rho) - BRAKE(brake)
		dx = np.zeros(12)

		# NAVIGATION EQUATIONS (NED velocities: xdot, ydot, zdot)
		dx[0], dx[1], dx[2] = navigationEquations(u, v, w, sphi, cphi, stet, ctet, spsi, cpsi)

		# EULER KINEMATIC EQUATIONS (euler angle rates: phidot, tetadot, psidot)
		dx[3], dx[4], dx[5] = kinematicEquations(p, q, r, sphi, cphi, ctet, ttet)

		# TRANSLATIONAL MOVEMENT EQUATIONS (translational accelerations: udot, vdot, wdot)
		dx[6], dx[7], dx[8] = translationalEquations(model["mass"], g, X, Y, Z, u, v, w, p, q, r, sphi, cphi, stet, ctet)

		# ROTATIONAL MOVEMENT EQUATIONS (angular accelerations: pdot, qdot, rdot)
		dx[9], dx[10], dx[11] = rotationalEquations(model["Ix"], model["Iy"], model["Iz"], model["Ixz"], l, m, n, p, q, r)

		return dx

	return f

def runSimulation(model, x0, t0, tf, dt):
    t = np.arange(t0, tf + dt, dt)

    x = np.zeros((12, len(t)))
    dx = np.zeros((12, len(t)))

    x[:, 0] = x0

    f = makeStateEq(model,[0,0,0])
    rk4(f, x, dx, t, dt)

    return t, x, dx