[inertia]
mass = 10.54
Ix = 0.19455601
Iy = 2.42736474
Iz = 0.52497209
Ixz = 0.09489698
x_cg = 0.3913
y_cg = 0.0
z_cg = 0.315

[geometry]
S = 0.7973
b = 1.9
c = 0.4209

[propulsion]
arm_z_engine = 0.001

[control_limits]
elevator_max = 25.0
aileron_max = 20.0
rudder_max = 30.0
brake_max = 200.0

[aero]
tables_dir = "C:/Users/enzo_/Documents/GitHub/fsimnew/Flight-Simulator/cases/mushu/aero_tables"

[ground_altitude]
alt = -635.3
