# cases/mushu/aircraft_model.toml
# All values in SI units.

# Inertia
[inertia]
mass = 9.848   # kg      — total mass
Ix   = 0.21441685042   # kg.m^2  — roll moment of inertia
Iy   = 0.37107404812   # kg.m^2  — pitch moment of inertia
Iz   = 0.50911049121   # kg.m^2  — yaw moment of inertia
Ixz  = 0.0654148776      # kg.m^2  — product of inertia (0 for symmetric aircraft)
x_cg = 0.2613
y_cg = 0.0
z_cg = 0.308

# Wing geometry
[geometry]
S = 0.7973   # m^2   wing reference area
b = 1.9   # m     wingspan
c = 0.4209   # m     mean aerodynamic chord

# Propulsion
[propulsion]
arm_z_engine = -0.006   # m    vertical distance from CG to thrust line
                        #     negative = thrust line above CG

# Control surface deflection limits
[control_limits]
elevator_max = 25.0   # deg
aileron_max  = 20.0   # deg
rudder_max   = 30.0   # deg
brake_max    = 200.0  # N

# Aerodynamic tables
[aero]
tables_dir = "C:/Users/enzo_/Documents/GitHub/Flight-Simulator/cases/mushu/aero_tables"   # path relative to this file

