# cases/mushu/plots.toml
# Each [[figure]] opens a new window.
# "groups" lists subplot lines. Maximum 3 lines.
# Available gropus:
#   Position, Velocity NED, Euler angles, Euler rates,
#   Angular velocity, Aerodynamics, Body velocity

[[figure]]
groups = ["Position", "Velocity NED"]

[[figure]]
groups = ["Euler angles", "Euler rates", "Angular velocity"]

[[figure]]
groups = ["Aerodynamics", "Body velocity"]
